
document.write('  <div class="sidebar">');
document.write('');
document.write('');
document.write('      <div>');
document.write('          <img src="/img/hakuAvatar.jpeg" alt="Haku\'s avatar" class="hakuAvatarImg">');
document.write('      </div>');
document.write('');

document.write('');
document.write('      <li><a href="/">Overview</a></li>');
document.write('');
document.write('      <div class="dropdown">');
document.write('          <button onclick="myFunction(\'dropdown1\')" class="dropbtn">&#xFE40 Street</button>');
document.write('          <div id="dropdown1" class="dropdown-content">');
document.write('              <a href="https://hakuuww.github.io/hakuGallerySite/pages/street/waterloo.html">Waterloo</a>');
document.write('              <a href="https://hakuuww.github.io/hakuGallerySite/pages/street/toronto.html">Toronto</a>');
document.write('              <a href="https://hakuuww.github.io/hakuGallerySite/pages/street/shanghai.html">Shanghai</a>');
document.write('          </div>');
document.write('      </div>');
document.write('');
document.write('      <div>');
document.write('          <ul>');
document.write('              <li><a href="/blog">Blog</a></li>');
document.write('              <li><a href="/contact">Contact</a></li>');
document.write('              <li><a href="/pages/about.html">About</a></li>');
document.write('      </div>');
document.write('');
document.write('      <div>');
document.write('          <div class="dropdown">');
document.write('              <button onclick="myFunction(\'dropdown2\')" class="dropbtn">&#xFE40 Others</button>');
document.write('              <div id="dropdown2" class="dropdown-content">');
document.write('                  <a href="#">Link 1</a>');
document.write('                  <a href="#">Link 2</a>');
document.write('                  <a href="#">Link 3</a>');
document.write('              </div>');
document.write('          </div>');
document.write('      </div>');
document.write('');
document.write('      <div class="theme-button">');
document.write('          <button id="theme-mode-toggle"><i id="icon" class="fa-regular fa-sun"></i></button>');
document.write('      </div>');
document.write('  </div>');
